config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root to: 'home#index'
    get '/',                        to: 'home#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'

    resources :products,            only: [:show] do
      collection do
        get 'search'
      end
    end
    resources :categories,          only: [:show]
    get 'cart',                     to: 'orders#edit'
    patch 'cart',                   to: 'orders#update'
    resources :line_items,          only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/option_value_decorator.rb
Spree::OptionValue.class_eval do
  scope :values_all, -> (value) { includes(:option_type).where(spree_option_types: { presentation: value }) }
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  def related_products
    Spree::Product.in_taxons(taxons).includes(master: [:default_price, :images]).where.not(id: id).distinct
  end

  def self.ransackable_attributes(auth_object = nil)
    %w(name description)
  end

  def ransackable_associations(auth_object = nil)
    %w(stores variants_including_master master variants)
  end

  scope :filter_by_option, -> (option) { joins(variants: :option_values).where(spree_option_values: { name: option }).distinct }
  scope :filter_by_order, -> (order) {
    case order
    when "arrivals_desc"
      order(available_on: :desc)
    when "arrivals_asc"
      order(available_on: :asc)
    when "low_price"
      order('spree_prices.amount asc')
    when "high_price"
      order('spree_prices.amount desc')
    end
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_search

  def set_search
    @q = Spree::Product.ransack(params[:q])
  end
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  helper_method :count_number_of_products_by_option
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.all.includes(:root)
    @colors = Spree::OptionValue.values_all("Color")
    @sizes = Spree::OptionValue.values_all("Size")

    if params[:option].present?
      @products =  @taxon.all_products.includes(master: [:default_price, :images]).filter_by_option(params[:option])
    elsif params[:order].present?
      @products =  @taxon.all_products.includes(master: [:default_price, :images]).filter_by_order(params[:order])
    else
      @products =  @taxon.all_products.includes(master: [:default_price, :images]).order(available_on: :desc)
    end
  end

  def count_number_of_products_by_option(option_value)
    @taxon.all_products.includes(variants: :option_values).where(spree_option_values: { name: option_value.name }).count
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  MAX_NEW_PRODUCTS = 10

  def index
    @new_products = Spree::Product.includes(master: [:default_price, :images]).order(available_on: :desc).limit(MAX_NEW_PRODUCTS)
  end
end

app/controllers/potepan/line_items_controller.rb
class Potepan::LineItemsController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  def create
    order = current_order(create_order_if_necessary: true)
    authorize! :update, order, cookies.signed[:guest_token]

    variant = Spree::Variant.find(params[:variant_id])
    quantity = params[:quantity].to_i

    if !quantity.between?(1, 2_147_483_647)
      order.errors.add(:base, t('spree.please_enter_reasonable_quantity'))
    end

    begin
      @line_item = order.contents.add(variant, quantity)
    rescue ActiveRecord::RecordInvalid => e
      order.errors.add(:base, e.record.errors.full_messages.join(","))
    end

    if order.errors.any?
      flash[:error] = order.errors.full_messages.join(",")
      redirect_back_or_default(spree.root_path)
      return
    else
      redirect_to potepan_cart_path
    end
  end

  def destroy
    item = Spree::LineItem.find(params[:id])
    item.order.contents.remove_line_item(item)
    redirect_to potepan_cart_path
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  def edit
    @order = current_order || Spree::Order.incomplete.find_or_initialize_by(guest_token: cookies.signed[:guest_token])
  end

  def update
    @order = Spree::Order.find_by(number: params[:number])
    @order.contents.update_cart(order_params)
    redirect_to potepan_cart_path
  end

  def order_params
    params.require(:order).permit(line_items_attributes: [:id, :quantity])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_DISPLAY_RELATED_PRODUCTS = 4

  def show
    @product = Spree::Product.find(params[:id])
    @product_properties = @product.product_properties.includes(:property)
    @related_products = @product.related_products.limit(MAX_DISPLAY_RELATED_PRODUCTS)
  end

  def search
    @search = @q.result.includes(master: [:default_price, :images]).page(params[:page])
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title: '')
    base_title = "BIGBAG"
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/views/layouts/_footer.html.erb
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header clearfix">
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12 form-inline">
          <ul class="list-inline pull-right">
            <li class="dropdown searchBox">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <%= search_form_for(@q, url: search_potepan_products_path, method: :get, enforce_utf8: false) do |f| %>
                    <span class="input-group form-inline">
                      <%= f.text_field :name_or_description_cont, class: "form-control", placeholder: "Search...", aria_describedby: "basic-addon2", id: "product_name" %>
                      <%= f.submit "検索", class: "input-group-addon addPointer", id: "basic-addon2" %>
                    </span>
                  <% end %>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to potepan_root_path, class: "navbar-brand" do %>
          <%= image_tag("img/logo.png", :alt => "") %>
        <% end %>
      </div>
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", potepan_root_path %></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_login_modal.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(page_title: yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/shim' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/login_modal' %>
    <%= render 'layouts/signup_modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_filter_by_color.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled" id="filter_by_color">
      <% colors.each do |color| %>
        <li>
          <%= link_to (potepan_category_path(id: taxon.id, color: color.name)) do %>
            <%= color.name %><span>(<%= count_number_of_products_by_option(color) %>)</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/categories/_filter_by_size.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled clearfix">
      <% sizes.each do |size| %>
        <li>
          <%= link_to (potepan_category_path(id: taxon.id, size: size.name)) do %>
            <%= size.presentation %><span>(<%= count_number_of_products_by_option(size) %>)</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/categories/_light_section_header.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_index_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_product.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <%= link_to potepan_product_path(product.id) do %>
      <div class="productImage clearfix">
        <%= image_tag(product.display_image.attachment(:product)) %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      </div>
    <% end %>
  </div>
</div>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>
<%= render 'potepan/categories/light_section_header', taxon: @taxon %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <div class="panel panel-default">
          <div class="panel-heading">商品カテゴリー</div>
          <div class="panel-body">
            <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
              <ul class="nav navbar-nav side-nav">
                <% @taxonomies.each do |taxonomy| %>
                  <li>
                    <%= link_to "javascript:;", data: {toggle: "collapse", target: "#category-#{taxonomy.id}"} do %>
                      <%= taxonomy.name %>
                      <i class="fa fa-plus"></i>
                    <% end %>
                    <ul id="category-<%= taxonomy.id %>" class="collapse collapseItem">
                      <% taxonomy.root.leaves.each do |leaf| %>
                        <li>
                          <%= link_to potepan_category_path(leaf.id) do %>
                            <i class="fa fa-caret-right" aria-hidden="true"></i>
                            <%= leaf.name %>
                            <span>(<%= leaf.products.count %>)<span>
                          <% end %>
                        </li>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <%= render 'potepan/categories/filter_by_color', colors: @colors, taxon: @taxon %>
        <%= render 'potepan/categories/filter_by_size', sizes: @sizes, taxon: @taxon %>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <%= form_with(url: request.path, method: :get, local: true) do |f| %>
              <%= f.select(:order, [["新着順", "arrivals_desc"], ["古い順", "arrivals_asc"], ["安い順", "low_price"],
                                  ["高い順", "high_price"]], selected: (params[:order] || "arrivals_desc"), class: "select-drop") %>
              <%= f.submit "絞り込み" %>
            <% end %>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
              <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
            </div>
          </div>
        </div>
        <div class="row">
          <%= render partial: 'product', collection: @products, as: :product %>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'potepan/categories/light_section_footer' %>

app/views/potepan/home/_main_content.html.erb
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row featuredCollection">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>人気カテゴリー</h4>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='single_product.html';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-01.jpg", :alt => "feature-collection-image") %>
            <div class="masking"><a href="product_grid_left_sidebar.html" class="btn viewBtn">View Shirts</a></div>
          </div>
          <div class="caption">
            <h4>Shirts</h4>
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='single_product.html';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-02.jpg", :alt => "feature-collection-image") %>
            <div class="masking"><a href="product_grid_left_sidebar.html" class="btn viewBtn">View Bags</a></div>
          </div>
          <div class="caption">
            <h4>Bags</h4>
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='single_product.html';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-03.jpg", :alt => "feature-collection-image") %>
            <div class="masking"><a href="product_grid_left_sidebar.html" class="btn viewBtn">View Denim</a></div>
          </div>
          <div class="caption">
            <h4>Denim</h4>
          </div>
        </div>
      </div>
    </div>
    <div class="row featuredProducts">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>新着商品</h4>
        </div>
      </div>
      <div class="col-xs-12">
        <div class="owl-carousel featuredProductsSlider">
            <% new_products.each do |new_product| %>
              <div class="slide">
                <%= link_to potepan_product_path(new_product.id) do %>
                  <div class="productImage">
                    <%= image_tag(new_product.display_image.attachment.url(:large)) %>
                  </div>
                  <div class="productCaption">
                    <h5><%= new_product.name %></h5>
                    <h3><%= new_product.display_price %></h3>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/orders/_line_item.html.erb
<%= order_form.fields_for :line_items, line_item do |line_item_fields| %>
  <tr>
    <td class="col-xs-2">
      <%= link_to potepan_line_item_path(line_item), class: "close", method: :delete do %>
        <span aria-hidden="true">&times;</span>
      <% end %>
      <span class="cartImage">
        <%= image_tag(line_item.variant.display_image.attachment(:small)) %>
      </span>
    </td>
    <td class="col-xs-4"><%= line_item.name %></td>
    <td class="col-xs-2"><%= line_item.display_price %></td>
    <td class="col-xs-2"><%= line_item_fields.number_field :quantity, min: 0 %></td>
    <td class="col-xs-2"><%= line_item.display_total %></td>
  </tr>
<% end %>s

app/views/potepan/products/_cart_form.html.erb
<%= form_for :order, url: potepan_line_items_path do |f| %>
  <% if product.variants.any? %>
    <span class='quick-drop'>
      <%= select_tag :variant_id, options_from_collection_for_select(product.varients, :id, :options_text), class: "select-drop" %>
    </span>
  <% else %>
    <%= hidden_field_tag "variant_id", @product.master.id %>
  <% end %>
  <span class="quick-drop resizeWidth">
    <%= select_tag :quantity, options_for_select([*1..5]), class: "select-drop" %>
  </span>
  <div class="btn-area">
    <%= button_tag(type: 'submit', class: 'btn btn-primary btn-block') do %>
      カートに入れる<i class="fa fa-angle-right" aria-hidden="true"></i>
    <% end %>
  </div>
<% end %>

app/views/potepan/products/_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= product.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_index_path %>
          </li>
          <li class="active"><%= product.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_main_content.html.erb
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% product.images.each_with_index do |image, index| %>
                  <div class="item <%= "active" if index.zero? %>" data-thumb="<%= index %>">
                    <%= image_tag(image.attachment.url(:large)) %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <% product.images.each_with_index do |image, index| %>
                    <div data-target="#carousel" data-slide-to="<%= index %>" class="thumb">
                      <%= image_tag(image.attachment.url(:product)) %>
                    </div>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li>
                <%= link_to potepan_category_path(product.taxons.first.id) do %><i class="fa fa-reply" aria-hidden="true"></i>
                  一覧ページへ戻る
                <% end %>
              </li>
            </ul>
            <h2><%= product.name %></h2>
            <h3><%= product.display_price %></h3>
            <p><%= product.description %></p>
            <%= render "cart_form", product: @product %>
            <div class="tab-content">
              <div id="details" class="tab-pane fade in active">
                <ul class="list-unstyled">
                  <% product_properties.each do |product_property| %>
                    <li><%= product_property.property.presentation %>: <%= product_property.value %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row productsContent">
        <div class="col-xs-12">
          <div class="page-header">
            <h4>関連商品</h4>
          </div>
          <%= render partial: 'related_product', collection: @related_products, as: :related_product %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_related_product.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox">
    <%= link_to potepan_product_path(related_product.id) do %>
      <div class="productImage clearfix">
        <%= image_tag related_product.display_image.attachment(:product) %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= related_product.name %></h5>
        <h3><%= related_product.display_price %></h3>
      </div>
    <% end %>
  </div>
</div>

app/views/potepan/products/search.html.erb
<% provide(:title, "Search products") %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div id="product_form">
          <div class="row productListSingle">
            <% if @search.present? %>
              <% @search.each do |product| %>
                <div class="col-xs-12">
                  <div class="media">
                    <div class="media-left">
                      <div id="carousel" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                          <% product.images.each_with_index do |image, i| %>
                            <div class="item <%= "active" if i.zero? %>" data-thumb="<%= i %>">
                              <%= image_tag(image.attachment.url(:large)) %>
                            </div>
                          <% end %>
                        </div>
                      </div>
                    </div>
                    <div class="media-body">
                      <h4 class="media-heading">
                        <%= link_to(product.name, potepan_product_path(product.id)) %>
                      </h4>
                      <p><%= product.description %></p>
                      <h3><%= product.display_price %></h3>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'potepan/home/light_section' %>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<%= render 'potepan/products/light_section', product: @product %>
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% @product.images.each_with_index do |image, index| %>
                  <div class="item <%= "active" if index.zero? %>" data-thumb="<%= index %>">
                    <%= image_tag(image.attachment.url(:large)) %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <% @product.images.each_with_index do |image, index| %>
                    <div data-target="#carousel" data-slide-to="<%= index %>" class="thumb">
                      <%= image_tag(image.attachment.url(:product)) %>
                    </div>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li>
                <%= link_to potepan_category_path(@product.taxons.first.id) do %><i class="fa fa-reply" aria-hidden="true"></i>
                  一覧ページへ戻る
                <% end %>
              </li>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <%= render "cart_form", product: @product %>
            <div class="tab-content">
              <div id="details" class="tab-pane fade in active">
                <ul class="list-unstyled">
                  <% @product_properties.each do |product_property| %>
                    <li><%= product_property.property.presentation %>: <%= product_property.value %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row productsContent">
        <div class="col-xs-12">
          <div class="page-header">
            <h4>関連商品</h4>
          </div>
          <%= render partial: 'related_product', collection: @related_products, as: :related_product %>
        </div>
      </div>
    </div>
  </div>
</section>